# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins

update_fastlane
min_fastlane_version("2.112.0")
default_platform(:android)

platform :android do
  desc "At any error, do:"
  error do |lane, exception|
  log_server("💥 `android` " + exception.message)
  end

  desc "Run automated tests"
  lane :test_branch do
    log_server("⏳ Testing `android` branch...")
    gradle(
      task: "test",
      build_type: "ReleaseUnitTest",
      flags: "--stacktrace --no-daemon"
    )
    log_server("🍻 `android` has passed all tests!")
  end

  desc "Assemble Release Candidate"
  lane :assemble_release_candidate do
    log_server("⏳ Assembling release candidate build for `android`...")
    build_android_app(task: "assembleRelease")
    send_fabric("android")
    create_version_file()
  end
end

def log_server(message)
  sh("curl -X POST https://trancosowiliam.herokuapp.com/api/logci -d '{ \"message\":\"#{message}\", \"project\":\"test\"}'")
end

def send_fabric(group)
  crashlytics(
    api_token: ENV["FABRIC_API_KEY"],
    build_secret: ENV["FABRIC_BUILD_SECRET"],
    groups: group,
    notes_path: "./fastlane/ReleaseNotes.txt"
  )
end

def create_version_file()
  gradle(
    task: "createVersionFile"
  )
end